version: '3.7'

services:
  merchant-api:
    container_name: merchant-api
    build:
      context: .
      target: DEV
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - merchant-api
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - merchant-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  merchant-pgadmin:
    container_name: merchant-pgadmin
    image: dpage/pgadmin4
    networks:
      - merchant-api
    depends_on:
      - postgres
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
networks:
  merchant-api:
volumes:
  pgdata:
